export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const FETCH_TODAY = 'FETCH_TODAY';
export const SET_PREVIOUS_MONTH = 'SET_PREVIOUS_MONTH';
export const SET_NEXT_MONTH = 'SET_NEXT_MONTH';
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';