export const OPEN_ADD_MODAL = "OPEN_ADD_MODAL";
export const OPEN_CURRENT_MODAL = "OPEN_CURRENT_MODAL";
export const OPEN_UPDATE_MODAL = "OPEN_UPDATE_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const SET_SELECTED_DAY = "SET_SELECTED_DAY";
export const FETCH_TODAY = "FETCH_TODAY";
export const SET_PREVIOUS_MONTH = "SET_PREVIOUS_MONTH";
export const SET_NEXT_MONTH = "SET_NEXT_MONTH";
export const SET_SELECTED_DATE = "SET_SELECTED_DATE";

export const SET_SCHEDULES = "SET_SCHEDULES";
export const ADD_SCHEDULE = "ADD_SCHEDULE";
export const SET_SELECTED_SCHEDULE = "SET_SELECTED_SCHEDULE";
export const UPDATE_SCHEDULE = "UPDATE_SCHEDULE";
export const REMOVE_SCHEDULE = "REMOVE_SCHEDULE";
